// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4x_kxbC4Rj0STmpn9y4ySG4nuP5a_W90',
    appId: '1:346271331846:web:296157c8ee77d21b49f587',
    messagingSenderId: '346271331846',
    projectId: 'sticky-flutter-shop-aaeed',
    authDomain: 'sticky-flutter-shop-aaeed.firebaseapp.com',
    storageBucket: 'sticky-flutter-shop-aaeed.firebasestorage.app',
    measurementId: 'G-B9GWM9KLY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqrdph28kXmleuZaCXAQKnIb0H0NuDe5U',
    appId: '1:346271331846:android:d4350429096fe04049f587',
    messagingSenderId: '346271331846',
    projectId: 'sticky-flutter-shop-aaeed',
    storageBucket: 'sticky-flutter-shop-aaeed.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4x_kxbC4Rj0STmpn9y4ySG4nuP5a_W90',
    appId: '1:346271331846:web:490ec6cdaba51e5949f587',
    messagingSenderId: '346271331846',
    projectId: 'sticky-flutter-shop-aaeed',
    authDomain: 'sticky-flutter-shop-aaeed.firebaseapp.com',
    storageBucket: 'sticky-flutter-shop-aaeed.firebasestorage.app',
    measurementId: 'G-P9BMEM3ZH0',
  );
}
